# Generated by Django 3.0.5 on 2020-05-17 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ответ')),
                ('correct', models.BooleanField(default=True)),
                ('weight', models.SmallIntegerField(default=0, verbose_name='Вес ответа в опроснике')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_block', models.CharField(choices=[('PL', 'Опросник'), ('TS', 'Тест')], default='TS', max_length=2, verbose_name='Тип тестов')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=264, null=True, verbose_name='Вопрос')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Картинка')),
                ('type_variant', models.CharField(choices=[('RO', 'Радиокнопка'), ('CX', 'Чекбокс')], default='RO', max_length=2, verbose_name='Выбор варианта')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='QuestionInBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField(default=0, verbose_name='Вес вопроса в тесте')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block', to='questions.Block', verbose_name='Блок')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='questions.Question', verbose_name='Вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(related_name='answer', to='questions.Answer', verbose_name='Ответы')),
                ('question_in_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_in_block', to='questions.QuestionInBlock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_in_question', to='questions.Question', verbose_name='Вопрос'),
        ),
    ]
