# Generated by Django 3.0.5 on 2020-05-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_count',
            field=models.SmallIntegerField(default=0, verbose_name='Question count'),
        ),
    ]
