# Generated by Django 3.0.5 on 2020-05-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_answer_answer_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_count',
        ),
        migrations.AddField(
            model_name='block',
            name='question_count',
            field=models.SmallIntegerField(default=0, verbose_name='Question count'),
        ),
    ]
