# Generated by Django 3.0.5 on 2020-05-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200518_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='poll_total',
            field=models.SmallIntegerField(default=0, verbose_name='Сумма ответов опросника'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='test_total',
            field=models.SmallIntegerField(default=0, verbose_name='Сумма ответо в тесте'),
        ),
    ]
