# Generated by Django 3.0.5 on 2020-05-22 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20200522_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=60, null=True, verbose_name='Имя пользователя')),
                ('poll_total', models.SmallIntegerField(default=0, verbose_name='Сумма ответов опросника')),
                ('test_total', models.SmallIntegerField(default=0, verbose_name='Сумма ответо в тесте')),
            ],
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='poll_total',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='test_total',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to='questions.UserProfile', verbose_name='Пользователь'),
        ),
    ]
