# Generated by Django 3.0.5 on 2020-05-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20200523_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Пользователь'),
        ),
    ]
