# Generated by Django 3.0.5 on 2020-05-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20200523_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Пользователь'),
        ),
    ]
