# Generated by Django 3.0.5 on 2020-05-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20200523_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='profile_user',
        ),
    ]
