# Generated by Django 3.0.5 on 2020-05-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20200523_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_answer',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_quest1ion',
            field=models.CharField(blank=True, default=None, max_length=264, null=True, verbose_name='Вопрос'),
        ),
    ]
