# Generated by Django 3.0.5 on 2020-05-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20200523_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_quest1ion',
            new_name='user_question',
        ),
    ]
