# Generated by Django 3.0.5 on 2020-05-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20200523_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_answer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_question',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
    ]
