# Generated by Django 3.0.5 on 2020-05-24 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20200524_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='current_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to='questions.UserProfile', verbose_name='Пользователь'),
        ),
    ]
