# Generated by Django 3.0.5 on 2020-05-24 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0015_auto_20200524_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='current_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
