# Generated by Django 3.0.5 on 2020-05-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_auto_20200526_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='block',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_block', to='questions.Block', verbose_name='Блок'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_question', to='questions.Question', verbose_name='Вопрос'),
        ),
    ]
