# Generated by Django 3.0.5 on 2020-05-27 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_auto_20200526_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='block',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_block', to='questions.Block', verbose_name='Блок'),
        ),
    ]
