# Generated by Django 3.0.5 on 2020-05-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_auto_20200530_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, height_field='300', upload_to='media', verbose_name='Картинка', width_field='400'),
        ),
    ]
