# Generated by Django 3.0.5 on 2020-05-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_auto_20200530_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_passed',
        ),
        migrations.AddField(
            model_name='block',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
