# Generated by Django 3.0.5 on 2020-06-01 12:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_auto_20200530_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Описание'),
        ),
    ]
