# Generated by Django 3.0.5 on 2020-06-03 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_auto_20200601_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Блок тестов', 'verbose_name_plural': 'Блоки тестов'},
        ),
        migrations.AlterModelOptions(
            name='questioninblock',
            options={'verbose_name': 'Вопрос в блоке', 'verbose_name_plural': 'Вопросы в блоке'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Статистика пользователя', 'verbose_name_plural': 'Статистика пользователей'},
        ),
        migrations.AddField(
            model_name='block',
            name='date_begin',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата начала теста'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=True, help_text='Ставим галочку, если необходимо учесть вес ответа'),
        ),
        migrations.AlterField(
            model_name='block',
            name='question_count',
            field=models.SmallIntegerField(default=0, help_text='Поле не заполнять', verbose_name='Question count'),
        ),
    ]
