# Generated by Django 3.0.5 on 2020-06-03 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0029_userprofile_is_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_passed',
        ),
    ]
