# Generated by Django 3.0.5 on 2020-06-05 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0030_remove_userprofile_is_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='date_begin',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала теста'),
        ),
    ]
