# Generated by Django 3.0.5 on 2020-06-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0031_auto_20200605_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='is_passed',
            field=models.BooleanField(default=False, help_text='Поставте галочку, для деактивации теста'),
        ),
    ]
