# Generated by Django 3.0.5 on 2020-06-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0032_auto_20200607_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='answer',
            field=models.ManyToManyField(blank=True, default='', related_name='user_answer', to='questions.Answer', verbose_name='Ответы'),
        ),
    ]
