# Generated by Django 3.0.5 on 2020-06-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0034_auto_20200612_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='block',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='question',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='question_in_block',
            field=models.ManyToManyField(blank=True, default='', related_name='question_in_block', to='questions.QuestionInBlock', verbose_name='Вопросы в блоке'),
        ),
    ]
