# Generated by Django 3.0.5 on 2020-06-15 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0036_userprofile_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='block',
        ),
    ]
