# Generated by Django 3.0.5 on 2020-06-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0039_auto_20200619_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioninblock',
            name='answer',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='answer',
            field=models.ManyToManyField(blank=True, default='', related_name='user_answer', to='questions.Answer', verbose_name='Ответы'),
        ),
    ]
