# Generated by Django 3.0.5 on 2020-06-21 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0040_auto_20200619_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioninblock',
            name='weight',
        ),
    ]
