# Generated by Django 3.0.5 on 2020-06-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0041_remove_questioninblock_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_full',
            field=models.BooleanField(default=False, verbose_name='Проверка заполненности'),
        ),
    ]
